### ISSUE TITLE
Decide for and add a license

### ISSUE THREAD

**Issue by michel-zimmer** [siliciumpowered/free-stuff-matrixbot#6]

**Comment by michel-zimmer** [comment]
Copyleft or something more permissive or even public domain (like)?


License class | My preferred license
--- | ---
[Public-domain-equivalent license](https://en.wikipedia.org/wiki/Public-domain-equivalent_license) | [The Unlicense](https://github.com/siliciumpowered/free-stuff-matrixbot/community/license/new?branch=master&template=unlicense)
[Permissive license](https://en.wikipedia.org/wiki/Permissive_license) | [Apache License 2.0](https://github.com/siliciumpowered/free-stuff-matrixbot/community/license/new?branch=master&template=apache-2.0)
[Copyleft license](https://en.wikipedia.org/wiki/Copyleft) | [GNU General Public License v3.0](https://github.com/siliciumpowered/free-stuff-matrixbot/community/license/new?branch=master&template=gpl-3.0)

I like public domain, but the other options are just as fine for me.

_(The links to the specific licenses are from GitHub and allow to add the license with a few simple clicks.)_

**Comment by albalitz** [comment]
I often use the MIT license, but to be honest I know too little about licensing to appropriately apply it to one of your classes (I _think_ it would be permissive?).  
I'm fine with public domain too.

**Comment by michel-zimmer** [comment]
Yes, MIT would be classified as permissive. (See the table here: https://en.wikipedia.org/wiki/Permissive_license , also for other "classes" of licenses)

**Comment by mspl13** [comment]
MIT seems fine to me. It covers all the important things but is also not too long (as e.g. the GNU GPL 3.0), making it easier to comprehend.

**Comment by michel-zimmer** [comment]
I don't think the length should be the deciding factor. It can be valued, but I'd like to decide on a license class first.

If we go for the permissive license class where MIT would be grouped (because you've both suggested MIT), then we have MIT vs. Apache because I'd prefer Apache actually because it's just like MIT but adds a few things on top:
- It's possible to use our work in patents.
    - Not relevant I guess, because why would our content ever be part of a patent?
- It's explicitly prohibited to use our trademarks (and similar constructs).
    - We don't have trademarks in the foreseeable future, but doesn't hurt and who knows?
- One has to state the changes.
    - That's the one I'm interested in. This means one could incorporate the changes more easily into upstream and that's the reason why I was convinced, why one should prefer Apache over MIT.

Regarding the license class:
- We don't need copyleft - this restricts a lot of people (who probably don't have an interest in this, but you never know)
- Permissive is cool, because is explicitly allows all the important things.
- Public domain like would allow even more, but we "give it away". (Which can be a good thing.)

If you suggest MIT, would you be also fine with Apache?

**Comment by albalitz** [comment]
> If you suggest MIT, would you be also fine with Apache?

I am.  
Also nice summary. :+1:

**Comment by mspl13** [comment]
Yup, sounds good!
